
name = "AutoContentFlow"
client_id = ""  # To be filled via env
client_secret = "" # To be filled via env
scopes = "write_content,read_content,write_files,read_files"
embedded = true

[auth]
redirect_urls = []

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[app_preferences]
url = "https://autocontentflow.replit.app/auth"
